import { component$ } from "@builder.io/qwik";

export const FirstMarquee = component$(() => {
  return (
    <marquee
      width="100%"
      direction="right"
      class="blink"
      scrollamount="25"
      behavior="scroll"
    >
      <h2>
        LAUNCH SEQUENCE INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE
        INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO
        HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE
        INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO
        HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE
        INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO
        HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE
        INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO
        HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE
        INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO
        HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE
        INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO
        HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE
        INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO
        HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE
        INITIATED • IT'S TIME TO HACK • LAUNCH SEQUENCE INITIATED • IT'S TIME TO
        HACK •
      </h2>
    </marquee>
  );
});
